### ISSUE TITLE
Links don't open in a new tab

### ISSUE THREAD

**Issue by ocdtrekkie** [johnbintz/dokuwiki-sandstorm#2]
Links to external sites in Sandstorm apps should have `target=_blank` so that they open in a new tab.

Ideally, of course, any modification for this should be as light as possible so that it doesn't break maintainability.

**Comment by johnbintz** [comment]
This should be fixed with https://github.com/johnbintz/dokuwiki-sandstorm/blob/master/local.protected.php#L21 which is in the next App Store release.

**Comment by ocdtrekkie** [comment]
It is!
